### ISSUE TITLE
Example fails to load font

### ISSUE THREAD

**Issue by Clyybber** [nyorain/rvg#4]
The example_glfw fails to run. I'm not sure if this is an error with my font configuration, but I never noticed any problems with my font configuration. It compiles just fine with no warnings. I tested this on arch-linux gcc8. The only change I made to the example was to set `useValidation` to false.

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not load font Roboto-Regular.ttf
zsh: abort (core dumped)  ./example/example_glfw```

**Comment by nyorain** [comment]
Ups, you're right, seems like some leftover from font experiments. Sorry and thanks for the notice! Should be fixed now.

**Comment by Clyybber** [comment]
Thank you for the ultra quick response.
I even had Roboto-Refular.ttf installed, but it seems one has to put it in the build directory.
Anyways thanks for this amazing library, I look forward to using it( and probably writing a nim wrapper around it)!
Cheers

**Comment by nyorain** [comment]
Thanks, feel free to ask all questions that arise! Retrieving system fonts is usually somewhat ugly and system dependent, rvg doesn't implement that (yet?) so yeah, the examples load their fronts from the example/ folder.
