### ISSUE TITLE
fail in compilation on Fedora 33 gcc 10.2.1

### ISSUE THREAD

**Issue by faizol** [nyorain/rvg#9]
Hi,
I can't get rvg to compile, with error as the following;
`../subprojects/dlg/include/dlg/dlg.h:93:3: error: expected primary-expression before ‘{’ token
   93 |   {DLG_DEFAULT_TAGS NULL, __VA_ARGS__, NULL}.begin()`

It seems that the macro with uniform initialization list can't be expanded, from code ;
`	#define DLG_CREATE_TAGS(...) std::initializer_list<const char*> \
		{DLG_DEFAULT_TAGS NULL, __VA_ARGS__, NULL}.begin()`

How should I go about it?

Thanks.

**Comment by faizol** [comment]
the same problem as outlined here;
https://github.com/nyorain/dlg/issues/6#issue-715318105
Using the solution as mentioned in the link.

closing the issue.
Thanks.

**Comment by nyorain** [comment]
Oh yeah, I forgot to actually update the dlg version back then, thanks for reminding me and sorry for the inconvenience. Compilation of this (including the glfw example) should be fixed now. I also added a note to the README that this isn't very actively maintained for the moment.
